# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
    push:
        branches: [ main ]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt-openj9'
                    cache: 'gradle'
            -   name: Make gradlew executable
                run: chmod +x ./gradlew
            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
            -   name: Test with Gradle
                uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
                with:
                    arguments: --stacktrace clean test
