# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
    push:
        branches: [ main ]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            TESTCONTAINERS_REUSE_ENABLE: true

        steps:
            -   name: Checkout the code
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt-openj9'
                    cache: 'gradle'

            -   name: Make gradlew executable
                run: chmod +x ./gradlew

            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@v1

            -   name: Test with Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: test
